import type { InvariantSpec } from "./types.js";

export const invariantSpec = [
  {
    key: "fx_conversion_basis_required",
    description: "FX rate must exist when cross-currency journal conversion is required.",
    severity: "critical",
    failurePolicy: "block",
    timing: "pre-commit",
    doctrineRef: "ias21_fx_conversion",
    resolutionRef: "resolve_missing_fx_rate",
    evidenceShape: ["fromCurrency", "toCurrency", "postingDate"],
  },
  {
    key: "journal_must_balance",
    description: "Journal debits and credits must balance.",
    severity: "critical",
    failurePolicy: "block",
    timing: "pre-commit",
    doctrineRef: "double_entry_balance",
    resolutionRef: "resolve_journal_imbalance",
    evidenceShape: ["journalEntryId", "debitTotal", "creditTotal"],
  },
  {
    key: "posting_period_must_be_open",
    description: "Journal posting date must fall into an open period.",
    severity: "critical",
    failurePolicy: "block",
    timing: "pre-commit",
    doctrineRef: "closed_period_block",
    resolutionRef: "resolve_closed_period_block",
    evidenceShape: ["postingDate", "periodId", "periodStatus"],
  },
  {
    key: "economic_effect_must_be_unique",
    description: "The flow must not duplicate a previously committed economic effect.",
    severity: "critical",
    failurePolicy: "block",
    timing: "pre-commit",
    doctrineRef: "economic_effect_uniqueness",
    resolutionRef: "resolve_duplicate_economic_effect",
    evidenceShape: ["economicEffectKey", "existingEventId"],
  },
  {
    key: "supersession_required_for_meaning_change",
    description: "Meaningful state replacement must point to the superseded record.",
    severity: "critical",
    failurePolicy: "block",
    timing: "post-commit",
    doctrineRef: "supersession_required_for_meaning_change",
    resolutionRef: "resolve_supersession_required_for_meaning_change",
    evidenceShape: ["entityId", "previousEventId", "newEventId"],
  },
] as const satisfies readonly InvariantSpec[];
