export type SalesRelationDefinition = {
  from: string;
  to: string;
  kind: "one-to-many" | "many-to-one" | "self-reference";
  fromField: string;
  toField: string;
};

export const salesRelations = {
  partnerHierarchy: {
    from: "partners",
    to: "partners",
    kind: "self-reference",
    fromField: "parent_id",
    toField: "id",
  },
  partnerToSalesOrders: {
    from: "partners",
    to: "sales_orders",
    kind: "one-to-many",
    fromField: "id",
    toField: "partner_id",
  },
  productCategoryParent: {
    from: "product_categories",
    to: "product_categories",
    kind: "self-reference",
    fromField: "parent_id",
    toField: "id",
  },
  productCategoryToProducts: {
    from: "product_categories",
    to: "products",
    kind: "one-to-many",
    fromField: "id",
    toField: "category_id",
  },
  salesOrderToLines: {
    from: "sales_orders",
    to: "sales_order_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "order_id",
  },
  salesOrderToStatusHistory: {
    from: "sales_orders",
    to: "sale_order_status_history",
    kind: "one-to-many",
    fromField: "id",
    toField: "order_id",
  },
  salesOrderToTaxSummary: {
    from: "sales_orders",
    to: "sale_order_tax_summary",
    kind: "one-to-many",
    fromField: "id",
    toField: "order_id",
  },
  productToSalesOrderLines: {
    from: "products",
    to: "sales_order_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "product_id",
  },
  partnerToAddresses: {
    from: "partners",
    to: "partner_addresses",
    kind: "one-to-many",
    fromField: "id",
    toField: "partner_id",
  },
  partnerToBankAccounts: {
    from: "partners",
    to: "partner_bank_accounts",
    kind: "one-to-many",
    fromField: "id",
    toField: "partner_id",
  },
  paymentTermToPartners: {
    from: "payment_terms",
    to: "partners",
    kind: "one-to-many",
    fromField: "id",
    toField: "default_payment_term_id",
  },
  paymentTermToLines: {
    from: "payment_terms",
    to: "payment_term_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "payment_term_id",
  },
  pricelistToItems: {
    from: "pricelists",
    to: "pricelist_items",
    kind: "one-to-many",
    fromField: "id",
    toField: "pricelist_id",
  },
  pricelistBaseToItems: {
    from: "pricelists",
    to: "pricelist_items",
    kind: "one-to-many",
    fromField: "id",
    toField: "base_pricelist_id",
  },
  productToPricelistItems: {
    from: "products",
    to: "pricelist_items",
    kind: "one-to-many",
    fromField: "id",
    toField: "product_id",
  },
  categoryToPricelistItems: {
    from: "product_categories",
    to: "pricelist_items",
    kind: "one-to-many",
    fromField: "id",
    toField: "categ_id",
  },
  orderLineToLineTaxes: {
    from: "sales_order_lines",
    to: "sale_order_line_taxes",
    kind: "one-to-many",
    fromField: "id",
    toField: "order_line_id",
  },
  partnerToTagAssignments: {
    from: "partners",
    to: "partner_tag_assignments",
    kind: "one-to-many",
    fromField: "id",
    toField: "partner_id",
  },
  tagToTagAssignments: {
    from: "partner_tags",
    to: "partner_tag_assignments",
    kind: "one-to-many",
    fromField: "id",
    toField: "tag_id",
  },
  taxGroupToTaxRates: {
    from: "tax_groups",
    to: "tax_rates",
    kind: "one-to-many",
    fromField: "id",
    toField: "tax_group_id",
  },
  taxRateToChildren: {
    from: "tax_rates",
    to: "tax_rate_children",
    kind: "one-to-many",
    fromField: "id",
    toField: "parent_tax_id",
  },
  taxRateToFiscalPositionTaxMaps: {
    from: "tax_rates",
    to: "fiscal_position_tax_maps",
    kind: "one-to-many",
    fromField: "id",
    toField: "tax_src_id",
  },
  taxRateToSaleOrderLineTaxes: {
    from: "tax_rates",
    to: "sale_order_line_taxes",
    kind: "one-to-many",
    fromField: "id",
    toField: "tax_id",
  },
  taxRateToSaleOrderTaxSummary: {
    from: "tax_rates",
    to: "sale_order_tax_summary",
    kind: "one-to-many",
    fromField: "id",
    toField: "tax_id",
  },
  taxGroupToSaleOrderTaxSummary: {
    from: "tax_groups",
    to: "sale_order_tax_summary",
    kind: "one-to-many",
    fromField: "id",
    toField: "tax_group_id",
  },
  fiscalPositionToTaxMaps: {
    from: "fiscal_positions",
    to: "fiscal_position_tax_maps",
    kind: "one-to-many",
    fromField: "id",
    toField: "fiscal_position_id",
  },
  fiscalPositionToAccountMaps: {
    from: "fiscal_positions",
    to: "fiscal_position_account_maps",
    kind: "one-to-many",
    fromField: "id",
    toField: "fiscal_position_id",
  },
  partnerToConsignmentAgreements: {
    from: "partners",
    to: "consignment_agreements",
    kind: "one-to-many",
    fromField: "id",
    toField: "partner_id",
  },
  paymentTermToConsignmentAgreements: {
    from: "payment_terms",
    to: "consignment_agreements",
    kind: "one-to-many",
    fromField: "id",
    toField: "payment_term_id",
  },
  consignmentAgreementToLines: {
    from: "consignment_agreements",
    to: "consignment_agreement_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "agreement_id",
  },
  consignmentAgreementToStockReports: {
    from: "consignment_agreements",
    to: "consignment_stock_reports",
    kind: "one-to-many",
    fromField: "id",
    toField: "agreement_id",
  },
  productToConsignmentAgreementLines: {
    from: "products",
    to: "consignment_agreement_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "product_id",
  },
  consignmentStockReportToLines: {
    from: "consignment_stock_reports",
    to: "consignment_stock_report_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "report_id",
  },
  productToConsignmentStockReportLines: {
    from: "products",
    to: "consignment_stock_report_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "product_id",
  },
  returnReasonCodeToReturnOrders: {
    from: "return_reason_codes",
    to: "return_orders",
    kind: "one-to-many",
    fromField: "id",
    toField: "reason_code_id",
  },
  partnerToReturnOrders: {
    from: "partners",
    to: "return_orders",
    kind: "one-to-many",
    fromField: "id",
    toField: "partner_id",
  },
  salesOrderToReturnOrders: {
    from: "sales_orders",
    to: "return_orders",
    kind: "one-to-many",
    fromField: "id",
    toField: "source_order_id",
  },
  returnOrderToLines: {
    from: "return_orders",
    to: "return_order_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "return_order_id",
  },
  salesOrderLineToReturnLines: {
    from: "sales_order_lines",
    to: "return_order_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "source_line_id",
  },
  productToReturnOrderLines: {
    from: "products",
    to: "return_order_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "product_id",
  },
  paymentTermToSubscriptionTemplates: {
    from: "payment_terms",
    to: "subscription_templates",
    kind: "one-to-many",
    fromField: "id",
    toField: "payment_term_id",
  },
  pricelistToSubscriptionTemplates: {
    from: "pricelists",
    to: "subscription_templates",
    kind: "one-to-many",
    fromField: "id",
    toField: "pricelist_id",
  },
  subscriptionTemplateToSubscriptions: {
    from: "subscription_templates",
    to: "subscriptions",
    kind: "one-to-many",
    fromField: "id",
    toField: "template_id",
  },
  subscriptionCloseReasonToSubscriptions: {
    from: "subscription_close_reasons",
    to: "subscriptions",
    kind: "one-to-many",
    fromField: "id",
    toField: "close_reason_id",
  },
  partnerToSubscriptions: {
    from: "partners",
    to: "subscriptions",
    kind: "one-to-many",
    fromField: "id",
    toField: "partner_id",
  },
  subscriptionToLines: {
    from: "subscriptions",
    to: "subscription_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "subscription_id",
  },
  subscriptionToLogs: {
    from: "subscriptions",
    to: "subscription_logs",
    kind: "one-to-many",
    fromField: "id",
    toField: "subscription_id",
  },
  productToSubscriptionLines: {
    from: "products",
    to: "subscription_lines",
    kind: "one-to-many",
    fromField: "id",
    toField: "product_id",
  },
  uomToSubscriptionLines: {
    from: "units_of_measure",
    to: "subscription_lines",
    kind: "one-to-many",
    fromField: "uom_id",
    toField: "uom_id",
  },
  userToSalesTeams: {
    from: "users",
    to: "sales_teams",
    kind: "one-to-many",
    fromField: "user_id",
    toField: "manager_id",
  },
  salesTeamToMembers: {
    from: "sales_teams",
    to: "sales_team_members",
    kind: "one-to-many",
    fromField: "id",
    toField: "team_id",
  },
  userToSalesTeamMembers: {
    from: "users",
    to: "sales_team_members",
    kind: "one-to-many",
    fromField: "user_id",
    toField: "user_id",
  },
  salesTeamToTerritories: {
    from: "sales_teams",
    to: "territories",
    kind: "one-to-many",
    fromField: "id",
    toField: "team_id",
  },
  territoryHierarchy: {
    from: "territories",
    to: "territories",
    kind: "self-reference",
    fromField: "parent_id",
    toField: "id",
  },
  userToTerritories: {
    from: "users",
    to: "territories",
    kind: "one-to-many",
    fromField: "user_id",
    toField: "default_salesperson_id",
  },
  territoryToRules: {
    from: "territories",
    to: "territory_rules",
    kind: "one-to-many",
    fromField: "id",
    toField: "territory_id",
  },
  commissionPlanToTiers: {
    from: "commission_plans",
    to: "commission_plan_tiers",
    kind: "one-to-many",
    fromField: "id",
    toField: "plan_id",
  },
  commissionPlanToEntries: {
    from: "commission_plans",
    to: "commission_entries",
    kind: "one-to-many",
    fromField: "id",
    toField: "plan_id",
  },
  salesOrderToCommissionEntries: {
    from: "sales_orders",
    to: "commission_entries",
    kind: "one-to-many",
    fromField: "id",
    toField: "order_id",
  },
  userToCommissionEntries: {
    from: "users",
    to: "commission_entries",
    kind: "one-to-many",
    fromField: "user_id",
    toField: "salesperson_id",
  },
} as const satisfies Record<string, SalesRelationDefinition>;
